"use client";

import { useEffect, useState } from "react";
import styles from "./DashboardReasoningOverlay.module.css";
import { apiFetch, getBusinessId } from "../lib/api";

type Evidence = { metric?: string; value?: string; metadata?: { change?: number } };
type KPI = { name: string; value: string | null; change?: string | null; period?: string };
type Reasoning = { title: string; value: string; change?: string; context: string; why: string; implication: string };

function findKpi(kpis: KPI[], ...names: string[]) {
  return kpis.find((k) => names.some((name) => k.name.toLowerCase().includes(name)) && k.period !== "all_time");
}

function metricReasoning(element: HTMLElement, kpis: KPI[], evidence: Evidence[]): Reasoning {
  const label = element.querySelector(".metricLabel")?.textContent?.trim() || "Business metric";
  const value = element.querySelector("strong")?.textContent?.trim() || "—";
  const key = label.toLowerCase();
  const revenue = evidence.find((item) => item.metric === "revenue");
  const revenueKpi = findKpi(kpis, "revenue");
  const aovKpi = findKpi(kpis, "average", "aov");

  if (key === "total revenue") return { title: label, value, context: "All imported sales data", why: "This is the cumulative revenue represented by the sales records currently stored for this business.", implication: "Use it as a scale indicator. For performance movement, use Current Month Revenue and investigate the customers or products driving the change." };
  if (key === "total invoices") return { title: label, value, context: "All imported sales data", why: "The sales layer reconciles exports at invoice level, so repeating an export does not simply count the same invoice again.", implication: "Invoice count gives transaction-volume context. Read it together with revenue and average invoice value." };
  if (key === "current month revenue") {
    const change = revenueKpi?.change ?? (revenue?.metadata?.change != null ? String(revenue.metadata.change * 100) : undefined);
    return { title: label, value, change: change ? `${Number(change) >= 0 ? "+" : ""}${Number(change).toFixed(0)}%` : undefined, context: "Current period vs previous comparable period", why: change ? `Revenue moved ${Number(change) >= 0 ? "up" : "down"} ${Math.abs(Number(change)).toFixed(0)}%. That movement is evidence of a change in performance, but it does not by itself establish the cause.` : "The current reporting period is compared with the previous comparable period.", implication: "Drill into customer and product performance before deciding whether the movement requires action." };
  }
  if (key === "average invoice value") return { title: label, value, change: aovKpi?.change ? `${Number(aovKpi.change) >= 0 ? "+" : ""}${Number(aovKpi.change).toFixed(0)}%` : undefined, context: "Current month", why: "Average invoice value is calculated from invoice-level sales rather than generated by the language model.", implication: "A change can reflect order size, pricing, product mix, or customer mix. Read it alongside revenue and invoice count." };
  return { title: label, value, context: "Business data currently available", why: "This metric is calculated from the canonical business data layer.", implication: "Use the relevant intelligence section to investigate the records behind this number." };
}

export default function DashboardReasoningOverlay() {
  const [reasoning, setReasoning] = useState<Reasoning | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const open = async (event: MouseEvent) => {
      const target = (event.target as HTMLElement).closest<HTMLElement>(".metric, .healthPanel");
      if (!target || !getBusinessId()) return;
      setLoading(true);
      try {
        const [contextResponse, kpiResponse] = await Promise.all([apiFetch(`/context/${getBusinessId()}`), apiFetch(`/kpis/sales/${getBusinessId()}`)]);
        const context = contextResponse.ok ? await contextResponse.json() : {};
        const kpis: KPI[] = kpiResponse.ok ? await kpiResponse.json() : [];
        if (target.classList.contains("healthPanel")) {
          const status = target.querySelector("h3")?.textContent?.trim() || "Business health";
          const signals = Array.isArray(context.signals) ? context.signals : [];
          const high = signals.filter((signal: Record<string, unknown>) => signal.severity === "high").length;
          const positive = signals.filter((signal: Record<string, unknown>) => signal.severity === "positive").length;
          setReasoning({ title: "Business health", value: status, context: `${high} priority concern${high === 1 ? "" : "s"} · ${positive} positive signal${positive === 1 ? "" : "s"}`, why: high ? `Business Brain currently detects ${high} high-priority signal${high === 1 ? "" : "s"}. The health verdict is a prioritization layer over those detected signals.` : "No high-priority warning signals are currently detected in the available business data.", implication: "Open Management Attention to see the underlying signals. Investigate the evidence there before taking action." });
        } else {
          setReasoning(metricReasoning(target, kpis, context.evidence || []));
        }
      } finally { setLoading(false); }
    };
    const keydown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setReasoning(null);
      if ((event.key === "Enter" || event.key === " ") && document.activeElement instanceof HTMLElement) {
        const target = document.activeElement.closest<HTMLElement>(".metric, .healthPanel");
        if (target) { event.preventDefault(); target.click(); }
      }
    };
    const markInteractive = () => document.querySelectorAll<HTMLElement>(".metric, .healthPanel").forEach((element) => {
      element.setAttribute("role", "button"); element.setAttribute("tabindex", "0"); element.style.cursor = "pointer";
      element.setAttribute("aria-label", `View reasoning for ${element.querySelector(".metricLabel")?.textContent?.trim() || element.querySelector("h3")?.textContent?.trim() || "this metric"}`);
    });
    document.addEventListener("click", open); document.addEventListener("keydown", keydown); markInteractive();
    const observer = new MutationObserver(markInteractive); observer.observe(document.body, { childList: true, subtree: true });
    return () => { document.removeEventListener("click", open); document.removeEventListener("keydown", keydown); observer.disconnect(); };
  }, []);

  if (!reasoning && !loading) return null;
  return <div className={styles.backdrop} onMouseDown={() => !loading && setReasoning(null)}>
    <section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="reasoning-title" onMouseDown={(event) => event.stopPropagation()}>
      <button className={styles.close} type="button" onClick={() => setReasoning(null)} aria-label="Close">×</button>
      {loading ? <div className={styles.loading}><span className={styles.eyebrow}>BUSINESS BRAIN</span><h2>Building the explanation…</h2><p>Checking the underlying business data.</p></div> : reasoning && <>
        <div className={styles.header}><span className={styles.eyebrow}>WHY THIS NUMBER?</span><h2 id="reasoning-title">{reasoning.title}</h2><div className={styles.value}>{reasoning.value}</div>{reasoning.change && <span className={styles.change}>{reasoning.change}</span>}</div>
        <div className={styles.context}>{reasoning.context}</div>
        <div className={styles.reasonBlock}><span>WHAT IT TELLS YOU</span><p>{reasoning.why}</p></div>
        <div className={styles.reasonBlock}><span>WHY IT MATTERS</span><p>{reasoning.implication}</p></div>
        <div className={styles.footer}>The explanation is grounded in Business Brain's current business data. A metric movement is not presented as a cause unless the underlying evidence establishes it.</div>
      </>}
    </section>
  </div>;
}
